services:
  server:
    image: acequity:latest
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/server/.env
      - ./public/:/server/public/
      - ./sqlite.db/:/server/sqlite.db
    environment:
      - DB_PATH=/server/sqlite.db
    restart: unless-stopped
