name: Update Stock Data

on:
  workflow_dispatch:
  schedule:
    - cron: "30 11 * * 1-5" # 5 PM IST (11:30 AM UTC) every weekday

jobs:
  update-stock-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python Dependencies
        run: |
          cd server
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get Stock Data
        run: |
          cd server
          python src/utils/getstockdata.py

      - name: Save Stock Data in JSON format
        run: |
          cd server
          python src/utils/savetojson.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        run: |
          git config user.name github-actions
          git config user.email arkorty@gmail.com
          git add client/constants/TICKERS.json client/public/data/
          git commit -m "chore: update stock data" || echo "No changes to commit"
          git push origin HEAD:master
