name: Update Data

on:
  workflow_dispatch:
  schedule:
    - cron: "30 11 * * 1-5" # 5 PM IST (11:30 AM UTC) every weekday

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Git LFS and Curl
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs curl
          git lfs install

      - name: Set Up Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python Dependencies
        run: |
          cd scraper
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Get Latest Securities List
        run: |
          cd scraper
          curl -LJO --compressed -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "https://nsearchives.nseindia.com/content/equities/sec_list.csv"

      - name: Download, Export Stock Data and Clean Up Stale JSON Files
        run: |
          cd scraper
          python src/main.py -n 8 --cleanup

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        run: |
          git config user.name github-actions
          git config user.email arkorty@gmail.com
          git add client/constants/TICKERS.json client/public/data/*.json
          git commit -m "[AUTO] chore: update data" || echo "No changes to commit"
          git push origin HEAD:main
